yandex {
  url = "https://market.yandex.ru/"
}

validation {
  max_page = 10
}

filters {
  brands = ["Apple"]
}

check{
expected_result_search = ["iPhone"]
}

catalog {
  category = "Электроника"
  subcategory = "Мобильные телефоны"
}

driver {
  chrome_driver_path = "C:\\Users\\Liliana\\OneDrive\\Desktop\\chromedriver.exe"
}